env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    CONFIG: config.sh


task:
  name: "Sync_script"
  timeout_in: 500m  
  container:
           image: ghcr.io/sushrut1101/docker:arch
           cpu: 8
           memory: 16G 

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Hasajapathirana/recovery-builder-test/main/Builder.sh)"
