env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    CONFIG: config.sh

load("cirrus", "env", "http")

def on_build_failed(ctx):
    url = env.get("SLACK_WEBHOOK_URL")
    if not url:
        return

    message = {
        "text": "https://cirrus-ci.com/build/{} failed!".format(ctx.payload.data.build.id)
    }

task:
  name: "Sync_script"
  timeout_in: 500m  
  container:
           image: ghcr.io/sushrut1101/docker:arch
           cpu: 8
           memory: 16G 

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Hasajapathirana/recovery-builder-test/main/Builder.sh)"
